[package]
name = "static-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
rust_gpiozero = "0.1.0"
serde = { version = "1.0", features = ["derive"] }